### ISSUE TITLE
1.18 compability

### ISSUE THREAD

**Issue by sphings79** [PyvesB/AntiWorldFly#28] opened 2021-12-03 08:24 UTC
**Is your feature request related to a problem? Please describe.**
A version wich is 1.18 compatible

**Describe the solution you'd like**
A version wich is 1.18 compatible

**Additional context**
nothing

**Comment by Sidpatchy** [comment] 2021-12-03 17:08
Is there anything that doesn't work? I'm not finding any issues. Are you running the most recent version of the plugin (v2.4.1)?

**Comment by sphings79** [comment] 2021-12-03 17:19
I was still able to fly

**Comment by Sidpatchy** [comment] 2021-12-03 17:28
Okay... are there any errors? What version are you using (run /awf info)? Which world are you trying and failing to block flight in (/awf world)? Upload your config file to [GitHub Gist](https://gist.github.com/) so I can see it.

I need more info to be able to reproduce a bug. If I can't reproduce your issue, I can't fix it.

**Comment by Sidpatchy** [comment] 2021-12-07 06:22
Given the absence of any news, I'm gonna go ahead and close this.

**Closed as completed by Sidpatchy** 2021-12-07 06:22 UTC
Labels: bug, invalid
