### ISSUE TITLE
Fix bug change the world allow fly!

### ISSUE THREAD

**Issue by vanthoi** [PyvesB/AntiWorldFly#3] opened 2016-08-31 18:26 UTC
If a player moves via the world allowed to fly. Then log out and log in again. But at login authme respawn on map deny fly. After logging in, players can fly in this map without the other's permission!

**Comment by PyvesB** [comment] 2016-09-03 16:35
Hello,

Thanks for you report, I'll look into this scenario. AuthMe is apparently not behaving as expected by the plugin.

Cheers,

Pyves

**Comment by PyvesB** [comment] 2016-09-09 18:07
Hello again,

Could you please check whether the new version 2.1 has solved your issue?

EDIT 17/09: no news for more than a week, assuming the problem is solved and closing the issue.

Cheers,

Pyves

**Closed as completed** 2016-09-17 07:57 UTC
Labels: bug
