### ISSUE TITLE
ERROR NULL

### ISSUE THREAD

**Issue by Likhydro** [PyvesB/AntiWorldFly#34] opened 2022-04-21 05:42 UTC
**I was in creative mode when I entered the server and the plugin dire gave this error.**

`[20:36:01]` [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'awf' in plugin AntiWorldFly v2.5.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:908) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2372) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2183) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2164) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1420) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1398) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.hm.antiworldfly.file.CommentedYamlConfiguration.getString(String, String)" because the return value of "com.hm.antiworldfly.AntiWorldFly.getPluginLang()" is null
	at com.hm.antiworldfly.command.HelpCommand.getHelp(HelpCommand.java:34) ~[AntiWorldFly-2.5.0.jar:?]
	at com.hm.antiworldfly.AntiWorldFly.onCommand(AntiWorldFly.java:449) ~[AntiWorldFly-2.5.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 21 more`

**Comment by Sidpatchy** [comment] 2022-04-22 21:13
It's looking like there's an issue with your lang file. Is it empty? Is there any sort of error on startup?

**Comment by Likhydro** [comment] 2022-04-29 21:07
I didn't make any adjustments

**Comment by Sidpatchy** [comment] 2022-05-03 01:33
I'm not able to reproduce this issue. I've tested on Purpur 1.18.2 build 1567 as I was not able to download the previous version. Have you updated your server since initially encountering the issue, and if so, is it still a problem?

**Comment by Sidpatchy** [comment] 2022-06-14 20:08
Given the absence of any news, I'm gonna go ahead and close this.

**Closed as completed by Sidpatchy** 2022-06-14 20:08 UTC
Labels: bug
